{% set name = "google-ads" %}
{% set version = "25.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google_ads-{{ version }}.tar.gz
  sha256: db67c2780dc772093dea15857c88e7c03d97a2cb3e8366969390975ebc8c4a5c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7,<3.12
    - pip
    - setuptools
  run:
    - python >=3.7,<3.12
    - google-auth-oauthlib >=0.3.0,<2.0.0
    - google-api-core >=2.13.0,<=3.0.0
    - googleapis-common-protos >=1.56.3,<2.0.0
    - grpcio >=1.59.0,<2.0.0
    - grpcio-status >=1.59.0,<2.0.0
    - proto-plus >=1.22.3,<2.0.0
    - pyyaml >=5.1,<7.0
    - setuptools >=40.3.0
    - protobuf >=4.25.0,<6.0.0

test:
  imports:
    - google
    - google.ads
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleads/google-ads-python
  summary: Client library for the Google Ads API
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleads/google-ads-python
  doc_url: https://developers.google.com/google-ads/api/docs/start

extra:
  recipe-maintainers:
    - xylar
